server {
    listen 10000;
    listen [::]:10000;

    server_name _;

    root /var/www/html/public;

    index index.php index.html;

    # Laravel application
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Laravel Reverb WebSocket endpoint
    location /app/ {
        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_pass http://127.0.0.1:8080;
    }

    # Laravel Reverb API endpoint
    location /apps/ {
        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;

        proxy_pass http://127.0.0.1:8080;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass 127.0.0.1:9000;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param SERVER_PORT $server_port;

        fastcgi_param HTTP_PROXY "";
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}